env:
  browser: true
  es2022: true
ignorePatterns:
  - static/
overrides:
  - files: ["*.mts"]
    parserOptions:
      sourceType: module
plugins: ['@typescript-eslint']
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  prefer-const:
    - error
    - destructuring: all
  quotes:
    - error
    - single
  semi:
    - error
    - always
  '@typescript-eslint/no-unused-vars':
    - error
    - args: none
  '@typescript-eslint/no-explicit-any':
    - off
